import streamlit as st

# Custom function for indented paragraphs
def paragraph(text, indent=1):
    tab = "&nbsp;" * 4 * indent
    st.markdown(f"{tab}{text}", unsafe_allow_html=True)

# --- Header ---
st.title("📂 Development Documentation")
st.divider()

# --- Section 1: Data Preparation ---
st.header("1. Data Preparation")
with st.expander("Show Details", expanded=True):
    paragraph("The dataset used in this project is a **Synthetic Customer Churn Dataset** generated by **Gemini AI**. It simulates real-world business scenarios where service providers need to track customer behavior.")
    
    st.subheader("🛠️ Preprocessing Pipeline")
    st.info("**Handling Missing Values:** Numerical gaps (e.g., Income) were filled using the **Median** to avoid outlier bias, while categorical gaps were labeled as **'Unknown'**.")
    st.info("**Feature Scaling:** We applied **StandardScaler** to normalize data (Age vs. Income), ensuring the Neural Network converges efficiently.")
    st.info("**Categorical Encoding:** Text-based data like 'Gender' was converted into numerical format using **One-Hot Encoding**.")

# --- Section 2: Algorithm Theory ---
st.header("2. Neural Network Architecture")
st.markdown("> This model utilizes a **Deep Learning** approach, specifically an **Artificial Neural Network (ANN)**, to capture non-linear relationships in customer data.")

col1, col2 = st.columns(2)
with col1:
    st.write("**Core Structure:**")
    st.write("- **Input Layer:** Receives preprocessed features.")
    st.write("- **Hidden Layers:** Multiple Dense layers to learn complex patterns.")
    st.write("- **Dropout Layers:** Applied to prevent *Overfitting* by randomly deactivating neurons.")

with col2:
    st.write("**Mathematical Logic:**")
    st.write("- **Optimizer:** Adam (Adaptive Moment Estimation).")
    st.write("- **Loss Function:** Binary Cross-Entropy.")
    st.write("- **Output Activation:** Sigmoid (to produce Churn Probability 0-1).")

# --- Section 3: Development Journey ---
st.header("3. Development Journey")
st.markdown("My development workflow focused on **Self-Learning** and **AI Collaboration**:")

# Using streamlit's status or containers to show steps
steps = [
    {"step": "Step 1: Research", "desc": "Used **Google Search** to understand the fundamentals of Churn Prediction and Neural Network best practices."},
    {"step": "Step 2: AI Prompting", "desc": "Consulted **Gemini AI** to generate a structured dataset and define the initial model architecture."},
    {"step": "Step 3: Implementation", "desc": "Developed the Python code using **TensorFlow/Keras**. Whenever I encountered bugs in VS Code, I asked **Gemini** to explain the error and provide a fix."},
    {"step": "Step 4: Iteration", "desc": "Refined the UI and Model parameters by comparing documentation from Google with Gemini's real-time suggestions."},
    {"step": "Step 5: Deployment", "desc": "Integrated the final model into **Streamlit** for an interactive user experience."}
]

for item in steps:
    with st.container(border=True):
        st.write(f"**{item['step']}**")
        st.write(item['desc'])

# --- Section 4: References ---
st.divider()
st.header("📚 References")
st.markdown("""
- **[Gemini AI (Google)](https://gemini.google.com/)** - Main collaborator for code generation, debugging, and dataset creation.
- **[Google Search](https://www.google.com/)** - Primary resource for researching Deep Learning tutorials.
- **[TensorFlow Documentation](https://www.tensorflow.org/)** - Reference for ANN implementation.
- **[Streamlit Gallery & Docs](https://docs.streamlit.io/)** - Guide for building the web interface.
""")

